services:
  backend:
    build: ./SpringLoginPage
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    networks:
      - app-network

  frontend:
    build: ./FramTech-master
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  fastapi:
    build: ./API
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
